### ISSUE TITLE
Concert Grand doesn't have enough bass

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/Keppy-Steinway-Piano#1]
Since the 6.20 update, I notice that the Concert Grand preset doesn't have enough bass. It just doesn't sound grand anymore.

**Comment by KaleidonKep99** [comment]
Actually, the bass ruined the sound of the piano completely.

I decided to reduce the bass to make it sound like a real grand piano (I played some pianos IRL, I know their real sound).

**Comment by KaleidonKep99** [comment]
So... No, I'm not going to ruin it again with exaggerated bass.

I suggest to check your audio equipment, because it might be defective or not good enough for professional audio editing.
